
FCN_NAME = 'acado_solver_sfun';

if ( ispc == 0 )
    IFLAGS  = [ '-lrt -I. -I./qpoases3/include  -I./qpoases3/src  -I./qpoases3/ ' ];
    CPPFLAGS  = [ IFLAGS, '-D__cpluplus -O -DLINUX CFLAGS="-fPIC -std=c99" -D__CODE_GENERATION__ ' ];
else
    IFLAGS  = [ '-I. -I./qpoases3/include  -I./qpoases3/src  -I./qpoases3/ ' ];
    CPPFLAGS  = [ IFLAGS, '-D__cpluplus -O -DWIN32  -Dinline="" -D__CODE_GENERATION__ ' ];
end

OBJECTS = [ 'qpoases3/src/QProblem.c ', ...
            'qpoases3/src/QProblemB.c ', ...
            'qpoases3/src/Bounds.c ', ...
            'qpoases3/src/Matrices.c ', ...
            'qpoases3/src/Constraints.c ', ...
            'qpoases3/src/Indexlist.c ', ...
            'qpoases3/src/Flipper.c ', ...
            'qpoases3/src/Utils.c ', ...
            'qpoases3/src/MessageHandling.c ', ...
            'qpoases3/src/Options.c ', ...
            'qpoases3/src/OQPinterface.c ', ...
            'acado_integrator.c ',...
            'acado_solver.c ',...
            'acado_qpoases3_interface.c ' ];


eval( [ 'mex -v -output ', FCN_NAME, ' ', CPPFLAGS, ' ', FCN_NAME, '.c ', OBJECTS] );
disp( [ FCN_NAME, '.', eval('mexext'), ' successfully created!'] );

clear IFLAGS CPPFLAGS OBJECTS

