<?xml version="1.0"?>
<robot name="kugle" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!--
     1. Create model with URDF: http://wiki.ros.org/urdf/Tutorials/Create%20your%20own%20urdf%20file
     2. Add controllable joints: http://wiki.ros.org/urdf/Tutorials/Building%20a%20Movable%20Robot%20Model%20with%20URDF
     3. Physical properties: http://wiki.ros.org/urdf/Tutorials/Adding%20Physical%20and%20Collision%20Properties%20to%20a%20URDF%20Model or http://gazebosim.org/tutorials/?tut=ros_urdf
     4. Use Macros: http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File
     5. Link to Gazebo: http://wiki.ros.org/urdf/Tutorials/Using%20a%20URDF%20in%20Gazebo
    -->

	<!-- Inspired from https://github.com/mindThomas/JetsonCar-Simulation/blob/master/jetsoncar_description/urdf/jetsoncar.xacro -->

	<xacro:include filename="$(find kugle_description)/urdf/parameters.xacro" />
	<xacro:include filename="$(find kugle_description)/urdf/functions.xacro" />
	<xacro:include filename="$(find kugle_description)/urdf/physical.xacro" />
	<xacro:include filename="$(find kugle_description)/urdf/joints.xacro" />
	<xacro:include filename="$(find kugle_description)/urdf/transmissions.xacro" />
	<xacro:include filename="$(find kugle_description)/urdf/materials.xacro" />

	<!-- Base link is at the contact point (hence ground level) -->
	<link name="base_link"/>


	<!--<link name="contact_point">
		<origin xyz="0 0 -${ball_radius}" rpy="0 0 0" />
	</link>

	<xacro:fixed_offset_joint parent="contact_point" child="base_link" offset="0 0 ${ball_radius}"/>--> <!-- contact_point needs to be parent since actuation will affect this point -->

	<link name="ball">
		<!--<inertial>
			<xacro:ball_inertial/>
		</inertial>-->
		<inertial>
			<!-- Add a fictious mass and inertia to emulate a unit point mass - this allows the Torque inputs to work as Acceleration inputs -->
			<origin xyz="0 0 0" rpy="0 0 0" /> <!-- origin (0,0,0) is in the center of the box -->
			<mass value="1.0" />
			<inertia ixx="1.0"
					 ixy="0"
					 ixz="0"
					 iyy="1.0"
					 iyz="0"
					 izz="1.0"
			/>
		</inertial>
		<collision>
			<xacro:ball_collision/>
		</collision>
		<visual>
			<material name="black"/>
			<xacro:ball_geometry/>
		</visual>
	</link>

	<xacro:fixed_offset_joint parent="base_link" child="ball" offset="0 0 ${ball_radius}"/>

	<link name="heading">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="0.001" />
			<inertia ixx="0.0"
					 ixy="0"
					 ixz="0"
					 iyy="0.0"
					 iyz="0"
					 izz="0.0"
			/>
		</inertial>
	</link>

	<joint name="yaw" type="continuous">
		<parent link="ball"/>
		<child link="heading"/>
		<origin xyz="0 0 0" rpy="0 0 0" /> <!-- offset from parent to child, so with direction based in parent frame -->
		<axis xyz="0 0 1"/>
		<!--<limit lower="-${pi}" upper="${pi}" effort="10" velocity="100"/>-->
	</joint>


	<link name="tilt">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="0.001" />
			<inertia ixx="0.0"
					 ixy="0"
					 ixz="0"
					 iyy="0.0"
					 iyz="0"
					 izz="0.0"
			/>
		</inertial>
	</link>

	<joint name="pitch" type="revolute">
		<parent link="heading"/>
		<child link="tilt"/>
		<origin xyz="0 0 0" rpy="0 0 0" /> <!-- offset from parent to child, so with direction based in parent frame -->
		<axis xyz="0 1 0"/>
		<limit lower="-${pi/2}" upper="${pi/2}" effort="10" velocity="100"/>
	</joint>

	<link name="robot">
		<!--<inertial>
			<xacro:robot_inertial/>
		</inertial>-->
		<inertial>
			<!-- Add a fictious mass and inertia to emulate a unit point mass - this allows the Torque inputs to work as Acceleration inputs -->
			<origin xyz="0 0 ${cylinder_height/2}" rpy="0 0 0" />
			<mass value="0.001" />
			<inertia ixx="0000000.0"
					 ixy="0"
					 ixz="0"
					 iyy="0000000.0"
					 iyz="0"
					 izz="0000000.0"
			/>
		</inertial>
		<!--<collision>
			<xacro:robot_geometry/>
		</collision>-->
		<visual>
			<material name="grey"/>
			<xacro:robot_geometry/>
			<!--<origin xyz="0 0 -${ball_radius}" rpy="0 0 ${pi/2}" />
			<geometry>
				<mesh filename="package://kugle_gazebo/models/kugle.dae" scale="1.0 1.0 1.0"/>
			</geometry>-->
		</visual>
	</link>

	<!--<xacro:fixed_offset_joint_rpy parent="base_link" child="robot" offset="0 0 ${ball_radius}" rpy="0.2 0 0" />-->
	<joint name="roll" type="revolute">
		<parent link="tilt"/>
		<child link="robot"/>
		<origin xyz="0 0 0" rpy="0 0 0" /> <!-- offset from parent to child, so with direction based in parent frame -->
		<axis xyz="1 0 0"/>
		<limit lower="-${pi/2}" upper="${pi/2}" effort="10" velocity="100"/>
	</joint>

	<link name="sick_left_link">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="0.001" />
			<inertia ixx="0.0"
					 ixy="0"
					 ixz="0"
					 iyy="0.0"
					 iyz="0"
					 izz="0.0"
			/>
		</inertial>
		<visual>
			<material name="grey"/>
			<xacro:lidar_geometry/>
		</visual>
	</link>

	<xacro:fixed_offset_joint_rpy parent="robot" child="sick_left_link" offset="0 0.123 0.33757" rpy="0 0 0" />

	<link name="sick_right_link">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<mass value="0.001" />
			<inertia ixx="0.0"
					 ixy="0"
					 ixz="0"
					 iyy="0.0"
					 iyz="0"
					 izz="0.0"
			/>
		</inertial>
		<visual>
			<material name="grey"/>
			<xacro:lidar_geometry/>
		</visual>
	</link>

	<xacro:fixed_offset_joint_rpy parent="robot" child="sick_right_link" offset="0 -0.123 0.33757" rpy="0 0 ${pi}" />

	<!-- Link Gazebo and ROS - this has to happen as the last thing -->
	<xacro:include filename="$(find kugle_description)/urdf/gazebo.xacro" />

	<!-- Add realsense camera link -->
	<!-- Note that this Realsense camera is not the correct one, hence the physical location (frames) of the different image streams will be different in real life -->
	<!-- Import macro for realsense-RS200 camera-->
	<xacro:include filename="$(find realsense_gazebo_plugin)/urdf/realsense-RS200.macro.xacro"/>
	<!-- Create camera instance -->
	<xacro:realsense-rs200 prefix="" parent="robot">
		<origin xyz="0.05 0 1.11" rpy="0 0.25 0" />
	</xacro:realsense-rs200>

</robot>
